### ISSUE TITLE
support compiling under windows in the future?

### ISSUE THREAD

**Issue by Daemon1992** [danheeks/PyCAM#1]
hi,will PyCAD and PyCAM support compiling under windows in the future?

**Comment by danheeks** [comment]
![PyCAM on Windows 21st May 2020](https://user-images.githubusercontent.com/901376/82525748-131fbc00-9b2a-11ea-8864-58addb862990.png)
Yes. I am doing much of my development of it on my Windows PC. But I didn't write donw the instructions. The tricky bit was that I had to build boost-python with ( shared libraries turned on ) for the version of Python I am using ( 3.6.5 32 bit ). The projects ( cad, geom, step, cam ) all have .sln files which I open in Visual Studio 2013 Community Edition. I'll write a wiki page...

**Comment by danheeks** [comment]
https://github.com/danheeks/PyCAM/wiki/Windows-build
